---
- name: clean docker
  hosts: all
  tasks:
    - name: prune non-dangling volumes, images and networks
      community.docker.docker_prune:
        containers: false
        images: true
        images_filters:
          dangling: false
        networks: true
        volumes: true
        builder_cache: false
