---
- name: Update ftr sites
  hosts: 192.168.1.80
  become: yes
  become_user: root
  tasks:
    - name: cd and pull
      command: git pull
      args:
        chdir: /home/nikhil/.fulltextrss/standard/
