---
- name: Update and upgrade apt packages
  hosts: all
  tasks:
    - name: Update all packages to their latest version
      when: ansible_pkg_mgr == 'apt'
      become: true
      become_user: root
      apt:
        name: "*"
        state: latest

    - name: Update packages with apt
      when: ansible_pkg_mgr == 'apt'
      become: true
      become_user: root
      apt:
        update_cache: yes

    - name: Update packages with yum
      when: ansible_pkg_mgr == 'yum'
      yum:
        name: "*"
        state: latest

    - name: Upgrade packages with apt
      when: ansible_pkg_mgr == 'apt'
      become: true
      become_user: root
      apt:
        upgrade: dist

    - name: Upgrade packages with yum
      when: ansible_pkg_mgr == 'yum'
      yum:
        name: "*"
        state: latest
        exclude: kernel*
